### PR TITLE
Energy calib

### PR DESCRIPTION
**Pull request by CJ-Wright**
Use 2theta motorized detector for energy calibration of the XPD beamline

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@danielballan

**Comment by danielballan** [comment]
My solution:

```python
# Sweep y across reversed y. Multiply the overlapping elements and take
# the mean.
autocorr = ([np.mean(y[-i:] * y[::-1][:i]) for i in np.arange(1, len(y))] +
            [np.mean(y[:-i] * y[::-1][i:]) for i in np.arange(1, len(y))])

# Find offset i that produced max autocorr.
# Ignore edges, effectively assuming that the true center is within
# the central two quartiles of the array's length.
margin = int(0.5 * len(y))
offset = margin + np.argmax(autocorr[margin:-margin])

center = np.sign(offset) * (len(y) - abs(offset)) // 2
```

This works on your test data, identifying a center of -5 for `y[10:]`, `y[:-10]`. I also tested positive and negative 5, 15, and 30 and got accurate results.

**Comment by CJ-Wright** [comment]
@danielballan This still has some more things in it.

**Comment by CJ-Wright** [comment]
Preempted by recent changes

**Pull request closed without merging**
